config/routes.rb
Rails.application.routes.draw do
   root 'home#index'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  
  
    resources :lists do
      resources :items

  end

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/list.rb
class List < ActiveRecord::Base
    belongs_to :user
    has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @users = User.all
    @lists = current_user.lists.all
    @items = []
    if @lists.any?
      @lists.each do |list|
        list.items.each do |item|
          @items << item
        end
      end
    end
    @items = @items.sort_by(&:updated_at).reverse.take(5)
  end

  def show
  end

  def new

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :list, only: [:new, :create, :destroy]

  def new
    @item = Item.new
  end

  def create
    @item = @list.items.create(item_params)
    redirect_to list_path(@list)
  end

  def edit
  end 

  def update
    @list = current_user.lists.find(params[:list_id])
    @item = @list.items.find(params[:id])
    if @item.update(item_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @item = @list.items.find(params[:id])
    @item.destroy
    redirect_to list_path(@list)
  end 


private 
  def item_params
    params.require(:item).permit(:name, :completed, :goal_dates)
  end 
  
  def list
    @list = List.find(params[:list_id])
  end
 

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :list, only: [:edit, :update, :destroy]

  def index
    @lists = current_user.lists.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to user_lists_path(current_user, @list)
    else
      render :edit
    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to '/'
    else
      render :new
    end
  end

  def destroy
    @list.destroy
    redirect_to '/'
  end

  private
    def list_params
      params.require(:list).permit(:name, :date)
    end


    def list
      @list = current_user.lists.find(params[:id])
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

     def sign_up_params
       params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
     end

     def account_update_params
       params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<div class="header center-align">
  <h1>The Bucket List</h1>
  <p>Where we make your dreams come true ...or else.</p>
  <br />
  <%= button_to "New List", new_list_path, :class => 'waves-effect waves-light btn'%>
  </div>
</div>
<br />
<div class='row bottom-half'>
  <div class="container col s12 m8 l8 current_user_list">
    <h2>Bucket Lists for user: <%= current_user.first_name %> </h2> 
    <% if current_user.lists.any? %>
      <% current_user.lists.each do |list| %>
      <div class="list_block center-align">
        <%= link_to "#{list.name.upcase}", list_path(list) %><br />
        <p>Items: <%= list.items.count %></p>
        <p>Date Created: <%= list.date %></p> 
      </div>
      <% end %>
    <% end %>
  </div>    
  <div class = 'center-align container col s12 m4 l4 offset-s6 all_users_lists'>
    <h2>Other Users Lists</h2>
    <% if @users.any? %>
      <% @users.each do |user| %>
        <% if user.lists.any? && user != current_user %>
          <% user.lists.each do |list| %>
            <div class= "container list_block">
              <%= link_to "#{list.name.upcase}", list_path(list) %><br />
              <p>Date Created: <%= list.date %> 
              <br/> Created by: <%= user.first_name.capitalize %>  </p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>        

<hr />

<br />
<div class= "recently_completed">
 
 <% @items.each do |item| %>
  <% if item.completed == true %>
    <p>Item: <%= item.name %> recently completed!</p>
  <% end %>
<% end %> 
</div>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Make a New Item For your Bucket List</h1>
<%= form_for [@list, @item] do |f| %>

<%= f.label :name %>
<%= f.text_field :name, placeholder: 'goal' %>

<%= f.label :goal_dates %>
<%= f.date_field :goal_dates %>

<%= f.submit %>

<% end %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Homemade+Apple' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= yield %>
<%= button_to 'Log Out', destroy_user_session_path, method: :delete, :class => 'waves-effect waves-light btn' %>
</body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Bucket List name: <%= @list.name %></h1>


<% if @items.any? %>
      <div class= "item_block">
        <ul>
        <% @items.each do |list| %>
          <%= item.name %>
        <% end %>
        </ul>
      </div>
<% else %>
  <h2>No Listed Items</h2>
  <hr />
<% end %>
<%= link_to 'New Item', new_user_list_item_path(current_user, @list)%></h5>

app/views/lists/new.html.erb
<div class = "list_page_container">
  <h1>Make a New Bucketlist</h1>
  <p class= "funny_title">Maybe you have a new sense of adventure, or maybe you're bored and are just making this webiste for fun.  whatever your case, make your list here</p>
  <div class = "new_list_container row"> 
    <div class = "col s8 offset-s2 col m4 offset-m4 col l4 offset-l4">
    <%= form_for @list, :html => {class: 'list_form'} do |f| %>
     
      <%= f.label :name %>
      <%= f.text_field :name, required: true, :class => 'form_color'  %>
      
      <%= f.label :date %>
      <%= f.date_field :date, required: true, :class => 'form_color' %>
      
      <%= f.submit "Create", :class => 'list_button' %>
    <% end %>
  </div>
  </div>

</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<% if @list.user_id == current_user.id %>
<%= button_to 'Delete this list', list_path(@list), method: :delete %>
<% end %>
<hr />
<% if @list.items.any? %>
  <% @list.items.each do |item| %>
    <div>
      <%= item.name %>
      <%= item.goal_dates %>
        <% if @list.user_id == current_user.id %>
          <%= form_for [@list, item] do |f| %>
          <%= f.check_box :completed, id: item.id %>
          <%= f.label 'completed', for: item.id%>
    
          <%= f.submit %>
       
          <%= button_to 'Delete', list_item_path(@list, item), method: :delete %>
        <% end %>
      <% end %>

    </div>
  <% end %>
<% else %>
  <h2> <%= link_to 'There are no items here so set some goals', new_list_item_path(@list) %> </h2>
<% end %>
<% if @list.user_id == current_user.id %> 
<%= link_to "Add Item", new_list_item_path(@list) %> |
<% end %>
<%= link_to 'Back', '/' %>